### ISSUE TITLE
Apple ][ version not working

### ISSUE THREAD

**Issue by audetto** [voidstar78/DestinyHunter#1]
I tried `dhunter.dsk` in AppleWin and AppleCommander and none of them likes it.

```
pi@raspberrypi:~/projects/ac $ java -jar AppleCommander-ac-1.6.0.jar -i ../disks/dhunter.dsk 
Error: DiskUnrecognizedException
com.webcodepro.applecommander.storage.DiskUnrecognizedException: DiskUnrecognizedException
	at com.webcodepro.applecommander.storage.Disk.getFormattedDisks(Disk.java:410)
	at com.webcodepro.applecommander.ui.ac.getDiskInfo(ac.java:574)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:120)
```

**Comment by voidstar78** [comment]
Thank You!! I see what happened -   I tried as well, and noticed the
resulting DSK file was only 114K instead of 140K.

The link at the DH site wasn't a "raw" link, so it ends up downloading the
HTML related to downloading the DSK rather than the DSK itself.   I've
corrected the link for the DSK, and will go back through all the other
links to make sure they are raw ones.      Ironic, the problem was sort of
like "downloading the pointer" instead of de-referencing and downloading
the data being pointed to :)


Sorry for that confusion.   Again, the link is now corrected at the main
Download page, but I am attaching the proper DSK also as another backup
option.    Without being a raw link, then you'd need to left-click the link
to go to github and click the "View Raw" or Download link at their site.
But that's very subtle and how would anyone know the difference (especially
if you right click and SaveAs and it gives what appears to be the proper
filename, instead of github calling it like "dhunter.dsk.html").

At least I've learned that between the WordPress host and github, I need to
be thorough about using those raw links.

Thank You again for pointing this out,

Steve

**Comment by audetto** [comment]
Yes, link works now.

**Comment by voidstar78** [comment]
Be warned, the Apple 2 build available now is very much a BETA :)   I am making various updates on the Apple 2 build today: joystick paddle support, beach symbol update, and a bug on the last stage that won't let it finish, correcting the beach symbol and some other cosmetic corrections.

**Comment by voidstar78** [comment]
The Apple 2 updates are finished, be sure to grab the newer DHUNTERA2.DSK  (added sound and joystick support, added hit-flicker to indicate being hit by creatures,  some timing/stamina re-balancing, and some cosmetic/symbol improvements).
